type Project = {
  sheet: string;
  title: string;
  tags: string[];
  spec: string;
  status: "public" | "private";
  repoUrl?: string;
  demoUrl?: string;
  note?: string;
};

const projects: Project[] = [
  {
    sheet: "01",
    title: "Raphael",
    tags: ["Python", "Multi-Agent", "Shared Memory"],
    spec: "A self-improving multi-agent platform — shared memory, event-driven orchestration, and operational tooling. CI covers quick checks, full suite runs, and Helm chart validation.",
    status: "private",
  },
  {
    sheet: "02",
    title: "Network Observatory",
    tags: ["Python", "OpenWrt", "Security"],
    spec: "AI-assisted network monitoring and remediation for OpenWrt — log analysis, settings audits, threat detection, and safe command-execution gates before anything touches production.",
    status: "private",
  },
  {
    sheet: "03",
    title: "Document Analysis Engine",
    tags: ["FastAPI", "Streamlit", "RAG", "Agents"],
    spec: "A RAG chatbot with a genuine tool-calling agent on top — it searches uploaded documents, reports knowledge-base stats, and generates charts, all decided by the model itself. Swappable LLM provider (OpenAI, Anthropic, or OpenRouter).",
    status: "public",
    repoUrl: "https://github.com/Yamai7354/document-analysis-engine",
    demoUrl: "https://document-analysis-engine-sfnomhnlrsnbnmrukcffr7.streamlit.app",
  },
  {
    sheet: "04",
    title: "Foreman",
    tags: ["Python", "CLI", "SQLite"],
    spec: "The toolkit behind this page — work-session tracking, auto-generated docs and architecture diagrams, GitHub repo scaffolding, all backed by SQLite instead of loose files.",
    status: "private",
    note: "This site's docs & diagrams were generated by Foreman itself.",
  },
];

function CornerMarks() {
  return (
    <>
      <span
        aria-hidden
        className="absolute -top-px -left-px h-3.5 w-3.5 border-t-2 border-l-2 border-amber/60"
      />
      <span
        aria-hidden
        className="absolute -bottom-px -right-px h-3.5 w-3.5 border-b-2 border-r-2 border-amber/60"
      />
    </>
  );
}

export default function Home() {
  return (
    <div className="flex-1 bp-grid">
      {/* Nav */}
      <header className="border-b border-grid">
        <div className="mx-auto max-w-6xl px-6 py-5 flex items-center justify-between">
          <a href="#top" className="flex items-center gap-2 font-display font-extrabold text-xl tracking-tight">
            <span className="text-amber">▣</span> FOREMAN&nbsp;LABS
          </a>
          <nav className="hidden sm:flex items-center gap-8 font-mono text-xs uppercase tracking-widest text-linework-dim">
            <a href="#work" className="hover:text-linework transition-colors">Work</a>
            <a href="#about" className="hover:text-linework transition-colors">About</a>
            <a href="#contact" className="hover:text-linework transition-colors">Contact</a>
          </nav>
        </div>
      </header>

      {/* Hero */}
      <section id="top" className="border-b border-grid">
        <div className="mx-auto max-w-6xl px-6 py-20 md:py-28">
          <div className="font-mono text-xs uppercase tracking-widest text-amber mb-6 flex flex-wrap gap-x-6 gap-y-1">
            <span>Rev 2026.08</span>
            <span className="text-linework-dim">Drawn by — Randy Johnson</span>
            <span className="text-linework-dim">Omaha, NE</span>
          </div>

          <h1 className="font-display font-extrabold leading-[0.95] text-[13vw] sm:text-[9vw] md:text-[6.4rem] tracking-tight uppercase">
            I build the
            <br />
            <span className="text-amber">systems</span>
            <br />
            other people just
            <br />
            talk about
          </h1>

          <p className="mt-8 max-w-xl text-lg text-linework-dim">
            AI agents, ops tooling, and document intelligence — designed,
            built, and shipped. Every project below is a working system, not
            a slide deck.
          </p>

          <div className="mt-10 flex flex-wrap gap-4">
            <a
              href="#work"
              className="bg-amber text-navy-deep font-mono text-sm font-semibold uppercase tracking-wide px-6 py-3 hover:bg-amber-dim transition-colors"
            >
              View the work
            </a>
            <a
              href="#contact"
              className="border border-grid font-mono text-sm font-semibold uppercase tracking-wide px-6 py-3 hover:border-amber/60 transition-colors"
            >
              Get in touch
            </a>
          </div>
        </div>
      </section>

      {/* Projects */}
      <section id="work" className="mx-auto max-w-6xl px-6 py-20 md:py-24">
        <div className="flex items-baseline justify-between mb-10 font-mono text-xs uppercase tracking-widest text-linework-dim">
          <span>Drawing set — projects</span>
          <span>04 sheets</span>
        </div>

        <div className="grid sm:grid-cols-2 gap-px bg-grid border border-grid">
          {projects.map((p) => (
            <article key={p.sheet} className="bp-sheet bg-navy p-6 md:p-8 flex flex-col">
              <CornerMarks />
              <div className="flex items-center justify-between font-mono text-xs uppercase tracking-widest text-slate mb-4">
                <span>Sheet {p.sheet} / 04</span>
                <span className={p.status === "public" ? "text-amber" : "text-slate"}>
                  {p.status === "public" ? "Public" : "Private repo"}
                </span>
              </div>

              <h3 className="font-display font-bold text-3xl md:text-4xl uppercase tracking-tight mb-3">
                {p.title}
              </h3>

              <div className="flex flex-wrap gap-2 mb-4">
                {p.tags.map((tag) => (
                  <span
                    key={tag}
                    className="font-mono text-[11px] uppercase tracking-wide border border-grid px-2 py-1 text-linework-dim"
                  >
                    {tag}
                  </span>
                ))}
              </div>

              <p className="text-sm text-linework-dim leading-relaxed flex-1">{p.spec}</p>

              {p.note && (
                <p className="mt-4 font-mono text-[11px] text-amber/80 italic">{p.note}</p>
              )}

              <div className="mt-6 flex flex-wrap gap-4 font-mono text-xs uppercase tracking-widest">
                {p.repoUrl && (
                  <a
                    href={p.repoUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-amber hover:underline underline-offset-4"
                  >
                    View repo →
                  </a>
                )}
                {p.demoUrl && (
                  <a
                    href={p.demoUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-amber hover:underline underline-offset-4"
                  >
                    Live demo →
                  </a>
                )}
                {!p.repoUrl && !p.demoUrl && (
                  <span className="text-slate">Available on request</span>
                )}
              </div>
            </article>
          ))}
        </div>
      </section>

      {/* About / capabilities */}
      <section id="about" className="border-t border-grid">
        <div className="mx-auto max-w-6xl px-6 py-20 md:py-24 grid md:grid-cols-[1fr_auto] gap-12">
          <div>
            <div className="font-mono text-xs uppercase tracking-widest text-amber mb-4">
              Spec sheet
            </div>
            <h2 className="font-display font-bold text-4xl md:text-5xl uppercase tracking-tight mb-6">
              What I actually do
            </h2>
            <p className="max-w-2xl text-linework-dim leading-relaxed">
              I design and build AI systems for small and mid-size
              businesses — automations that connect your existing tools,
              chatbots and assistants trained on your business, and the
              unglamorous infrastructure (monitoring, tooling, ops) that
              keeps it all running. If it needs to work in production, not
              just in a demo, that&apos;s the job.
            </p>
          </div>
          <dl className="font-mono text-xs uppercase tracking-widest space-y-4 self-start md:border-l md:border-grid md:pl-8">
            <div>
              <dt className="text-slate">Stack</dt>
              <dd className="text-linework mt-1 normal-case">Python, FastAPI, Next.js, SQLite/Postgres, LangChain</dd>
            </div>
            <div>
              <dt className="text-slate">Focus</dt>
              <dd className="text-linework mt-1 normal-case">AI agents · automation · document intelligence</dd>
            </div>
            <div>
              <dt className="text-slate">Based in</dt>
              <dd className="text-linework mt-1 normal-case">Omaha, Nebraska</dd>
            </div>
          </dl>
        </div>
      </section>

      {/* Contact / footer */}
      <footer id="contact" className="border-t border-grid">
        <div className="mx-auto max-w-6xl px-6 py-16 md:py-20">
          <div className="font-mono text-xs uppercase tracking-widest text-amber mb-4">
            Approved for contact
          </div>
          <h2 className="font-display font-bold text-4xl md:text-5xl uppercase tracking-tight mb-6">
            Let&apos;s build something
          </h2>
          <a
            href="mailto:Randy.johnson7354@outlook.com"
            className="font-mono text-lg text-linework hover:text-amber transition-colors underline underline-offset-4"
          >
            Randy.johnson7354@outlook.com
          </a>
          <div className="mt-16 pt-6 border-t border-grid flex flex-wrap justify-between gap-4 font-mono text-[11px] uppercase tracking-widest text-slate">
            <span>© 2026 Randy Johnson</span>
            <span>Sheet 01/01 — Rev 2026.08</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
