"""
Documentation Generator - Auto-generate documentation for projects.

Features:
- Generate README.md from project structure
- Extract API documentation from docstrings
- Create project overviews
"""

import ast
from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Template
from rich.console import Console

from .utils import (
    display_panel,
    find_python_files,
    get_project_type,
    log_info,
    log_success,
    log_warning,
    read_file_safely,
)

console = Console()


# ============================================================================
# README Templates
# ============================================================================

DEFAULT_README_TEMPLATE = """# {{ project_name }}

{{ description }}

## Features

{% for feature in features %}
- {{ feature }}
{% endfor %}

## Installation

```bash
{{ install_command }}
```

## Usage

```{{ code_lang }}
{{ usage_example }}
```

## Project Structure

```
{{ structure }}
```

{% if api_reference %}
## API Reference

{{ api_reference }}
{% endif %}

## License

{{ license }}

---
*Generated by Foreman on {{ generated_date }}*
"""


# ============================================================================
# Code Analysis
# ============================================================================

class PythonAnalyzer:
    """Analyze Python files for documentation extraction."""

    def __init__(self, file_path: Path):
        self.file_path = file_path
        self.content = read_file_safely(file_path) or ""
        self.tree = None
        try:
            self.tree = ast.parse(self.content)
        except SyntaxError:
            pass

    def get_module_docstring(self) -> Optional[str]:
        """Get the module-level docstring."""
        if self.tree and self.tree.body:
            first = self.tree.body[0]
            if isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant):
                return first.value.value
        return None

    def get_classes(self) -> list[dict]:
        """Get all classes with their docstrings and methods."""
        if not self.tree:
            return []

        classes = []
        for node in ast.walk(self.tree):
            if isinstance(node, ast.ClassDef):
                methods = []
                for item in node.body:
                    if isinstance(item, ast.FunctionDef):
                        methods.append({
                            "name": item.name,
                            "docstring": ast.get_docstring(item),
                            "args": [arg.arg for arg in item.args.args if arg.arg != "self"],
                            "lineno": item.lineno
                        })

                classes.append({
                    "name": node.name,
                    "docstring": ast.get_docstring(node),
                    "methods": methods,
                    "lineno": node.lineno
                })
        return classes

    def get_functions(self) -> list[dict]:
        """Get all top-level functions with their docstrings."""
        if not self.tree:
            return []

        functions = []
        for node in self.tree.body:
            if isinstance(node, ast.FunctionDef):
                functions.append({
                    "name": node.name,
                    "docstring": ast.get_docstring(node),
                    "args": [arg.arg for arg in node.args.args],
                    "lineno": node.lineno
                })
        return functions


def analyze_project(project_path: Path) -> dict:
    """Analyze a project and extract documentation info."""
    project_path = Path(project_path)
    # Path(".").name is '' — resolve to an absolute path first so passing
    # "." (the common case) still yields the real directory name.
    resolved_name = project_path.resolve().name

    info = {
        "name": resolved_name,
        "type": get_project_type(project_path),
        "files": [],
        "classes": [],
        "functions": [],
        "readme_exists": (project_path / "README.md").exists(),
    }

    # Analyze Python files
    python_files = find_python_files(project_path)
    for py_file in python_files:
        # Skip hidden dirs and venv
        if any(part.startswith('.') or part in ('venv', '.venv', '__pycache__', 'node_modules')
               for part in py_file.parts):
            continue

        analyzer = PythonAnalyzer(py_file)
        rel_path = py_file.relative_to(project_path)

        file_info = {
            "path": str(rel_path),
            "docstring": analyzer.get_module_docstring(),
        }
        info["files"].append(file_info)

        for cls in analyzer.get_classes():
            cls["file"] = str(rel_path)
            info["classes"].append(cls)

        for func in analyzer.get_functions():
            func["file"] = str(rel_path)
            info["functions"].append(func)

    return info


def generate_structure_tree(project_path: Path, max_depth: int = 3) -> str:
    """Generate a tree view of project structure."""
    project_path = Path(project_path)
    lines = [project_path.name + "/"]

    def add_items(path: Path, prefix: str = "", depth: int = 0):
        if depth >= max_depth:
            return

        items = sorted(path.iterdir(), key=lambda x: (x.is_file(), x.name))
        items = [i for i in items if not i.name.startswith('.')
                 and i.name not in ('__pycache__', 'node_modules', '.venv', 'venv', '.git')]

        for i, item in enumerate(items):
            is_last = i == len(items) - 1
            connector = "└── " if is_last else "├── "
            lines.append(prefix + connector + item.name + ("/" if item.is_dir() else ""))

            if item.is_dir():
                extension = "    " if is_last else "│   "
                add_items(item, prefix + extension, depth + 1)

    add_items(project_path)
    return "\n".join(lines)


# ============================================================================
# CLI Functions
# ============================================================================

def generate_documentation(project_path: str, output: Optional[str], format: str):
    """Generate comprehensive documentation for a project."""
    project_path = Path(project_path)
    log_info(f"Analyzing project: {project_path.name}")

    info = analyze_project(project_path)

    # Display summary
    console.print(f"\n[bold]Project:[/bold] {info['name']}")
    console.print(f"[bold]Type:[/bold] {info['type']}")
    console.print(f"[bold]Python Files:[/bold] {len(info['files'])}")
    console.print(f"[bold]Classes:[/bold] {len(info['classes'])}")
    console.print(f"[bold]Functions:[/bold] {len(info['functions'])}")

    # Generate docs
    output_path = Path(output) if output else project_path / "docs"
    output_path.mkdir(parents=True, exist_ok=True)

    # Write API reference
    api_doc = generate_api_markdown(info)
    api_file = output_path / "API.md"
    api_file.write_text(api_doc, encoding="utf-8")
    log_success(f"API docs written to: {api_file}")

    # Write project overview
    overview = f"# {info['name']} - Project Overview\n\n"
    overview += f"**Type:** {info['type']}\n\n"
    overview += "## Structure\n\n```\n" + generate_structure_tree(project_path) + "\n```\n"

    overview_file = output_path / "OVERVIEW.md"
    overview_file.write_text(overview, encoding="utf-8")
    log_success(f"Overview written to: {overview_file}")


def generate_readme(project_path: str, template: str = "default"):
    """Generate a README.md for a project."""
    project_path = Path(project_path)
    log_info(f"Generating README for: {project_path.name}")

    info = analyze_project(project_path)

    # Detect features from code
    features = []
    for cls in info["classes"][:5]:
        if cls["docstring"]:
            features.append(cls["docstring"].split('\n')[0])
    for func in info["functions"][:5]:
        if func["docstring"]:
            features.append(func["docstring"].split('\n')[0])

    if not features:
        features = ["Feature 1 - Add description", "Feature 2 - Add description"]

    # Generate install command based on project type
    if info["type"] == "python":
        install_command = "pip install -e ."
        code_lang = "python"
        usage_example = f"from {info['name']} import main\n\nmain()"
    elif info["type"] == "node":
        install_command = "npm install"
        code_lang = "javascript"
        usage_example = f"const {info['name']} = require('{info['name']}');"
    else:
        install_command = "# Add installation instructions"
        code_lang = "bash"
        usage_example = "# Add usage example"

    # Render template
    tmpl = Template(DEFAULT_README_TEMPLATE)
    readme_content = tmpl.render(
        project_name=info["name"],
        description=f"A {info['type']} project.",
        features=features,
        install_command=install_command,
        code_lang=code_lang,
        usage_example=usage_example,
        structure=generate_structure_tree(project_path, max_depth=2),
        api_reference="See [API.md](docs/API.md) for detailed API documentation." if info["classes"] or info["functions"] else "",
        license="MIT",
        generated_date=datetime.now().strftime("%Y-%m-%d")
    )

    # Write README
    readme_path = project_path / "README.md"

    if readme_path.exists():
        log_warning("README.md already exists. Writing to README.generated.md")
        readme_path = project_path / "README.generated.md"

    readme_path.write_text(readme_content, encoding="utf-8")
    log_success(f"README written to: {readme_path}")

    # Display preview
    display_panel("README Preview", readme_content[:1000] + "..." if len(readme_content) > 1000 else readme_content)


def generate_api_docs(project_path: str, output: Optional[str]):
    """Extract API documentation from code."""
    project_path = Path(project_path)
    log_info(f"Extracting API docs from: {project_path.name}")

    info = analyze_project(project_path)
    api_doc = generate_api_markdown(info)

    # Write output
    if output:
        output_path = Path(output)
    else:
        output_path = project_path / "docs" / "API.md"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(api_doc, encoding="utf-8")

    log_success(f"API documentation written to: {output_path}")
    console.print(f"\n[bold]Classes documented:[/bold] {len(info['classes'])}")
    console.print(f"[bold]Functions documented:[/bold] {len(info['functions'])}")


def generate_api_markdown(info: dict) -> str:
    """Generate API reference in Markdown format."""
    lines = [
        f"# {info['name']} - API Reference",
        "",
        f"*Auto-generated on {datetime.now().strftime('%Y-%m-%d')}*",
        "",
    ]

    # Classes section
    if info["classes"]:
        lines.extend(["## Classes", ""])

        for cls in info["classes"]:
            lines.append(f"### `{cls['name']}`")
            lines.append(f"*Defined in: {cls['file']}:{cls['lineno']}*")
            lines.append("")

            if cls["docstring"]:
                lines.append(cls["docstring"])
                lines.append("")

            if cls["methods"]:
                lines.append("**Methods:**")
                lines.append("")
                for method in cls["methods"]:
                    args_str = ", ".join(method["args"]) if method["args"] else ""
                    lines.append(f"#### `{method['name']}({args_str})`")
                    if method["docstring"]:
                        lines.append(f"> {method['docstring']}")
                    lines.append("")

            lines.append("---")
            lines.append("")

    # Functions section
    if info["functions"]:
        lines.extend(["## Functions", ""])

        for func in info["functions"]:
            args_str = ", ".join(func["args"]) if func["args"] else ""
            lines.append(f"### `{func['name']}({args_str})`")
            lines.append(f"*Defined in: {func['file']}:{func['lineno']}*")
            lines.append("")

            if func["docstring"]:
                lines.append(func["docstring"])
            lines.append("")
            lines.append("---")
            lines.append("")

    return "\n".join(lines)
